config/routes.rb
MusicApp::Application.routes.draw do
  root to: redirect("/bands")
  

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:create, :show, :new]
  resources :tracks, except: [:index, :new]
  resources :notes, only: [:create, :destroy]
  
  resources :bands do
    resources :albums, only: [:new]
  end
  
  resources :albums, except: [:index] do
    resources :tracks, only: [:new]
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :name, :band_id, :year, presence: true 
  validates :name, uniqueness: { scope: :band_id }
  
  belongs_to :band
  has_many :tracks, dependent: :destroy
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true
  
  has_many :albums, dependent: :destroy
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :track
  belongs_to :user
  
  validates :track_id, :user_id, :content, presence: true
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :name, :album_id, :track_num, :lyrics, presence: true
  validates :track_num, uniqueness: { scope: :album_id }
  
  belongs_to :album
  has_one :band, through: :album, source: :band
  has_many :notes, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  
  after_initialize :set_session_token!
  
  
  def self.generate_session_token
    token = SecureRandom.base64(16)
  end
  
  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return nil unless user
    user.is_password?(password) ? user : nil
  end
  
  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end
  
  def set_session_token!
    self.session_token = self.class.generate_session_token
  end
  
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_user!
  
  def new
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: params[:band_id])
    render :new
  end
  
  def create
    @album = Album.new(album_params)
    
    if @album.save
      redirect_to album_url(@album)
    else
      @band = @album.band
      render :new
    end
  end
  
  def edit
    @album = Album.find(params[:id])
    render :edit
  end
  
  def show
    @album = Album.find(params[:id])
    render :show
  end
  
  def update
    @album = Album.find(params[:id])
    
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      render :edit
    end
  end
  
  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end
  
  private
  def album_params
    params.require(:album).permit(:name, :band_id, :year)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?, :default_album
  
  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def default_album
    @album = Album.all.first
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end
  
  def require_user!
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_user!
  
  def index
    @bands = Band.all
    render :index
  end
  
  def create
    @band = Band.new(band_params)
    
    if @band.save
      redirect_to band_url(@band)
    else
      render :new
    end
  end
  
  def new
    @band = Band.new
    render :new
  end
  
  def edit
    @band = Band.find(params[:id])
    render :edit
  end
  
  def show
    @band = Band.find(params[:id])
    render :show
  end
  
  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      render :edit
    end
  end
  
  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end
  
  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.save
    
    redirect_to track_url(@note.track_id)
  end
  
  def destroy
    @note = Note.find(params[:id])
    
    if @note.user_id == current_user.id
      @note.destroy
      redirect_to track_url(@note.track_id)
    else
      #do something
    end
  end
  
  private
  def note_params
    params.require(:note).permit(:track_id, :content)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    
    if user.nil?
      render :new
    else
      log_in_user!(user)
      redirect_to user_url(user)
    end
  end
  
  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    
    redirect_to new_session_url
  end
  
  def new
    render :new
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_user!
  
  def new
    @album = Album.find(params[:album_id])
    @track = Track.new(album_id: params[:album_id])
    render :new
  end
  
  def create
    @track = Track.new(track_params)
    
    if @track.save
      redirect_to track_url(@track)
    else
      @album = @track.album
      render :new
    end
  end
  
  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end
  
  def update
    @track = Track.find(params[:id])
    
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to album_url(@track.album_id)
  end
  
  private
  def track_params
    params.require(:track).permit(:name, :album_id, :track_num, :lyrics)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    
    if @user.save
      log_in_user!(@user)
      redirect_to root_url
    else
      render :new
    end
  end
  
  def new
    @user = User.new
    render :new
  end
  
  def show
    @user = User.find(params[:id])
    render :show
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def ugly_lyrics(lyrics)
    better_format = ""
    lyrics.lines.each do |line|
      better_format << "&#9835; #{h(line)}"
    end
    
    "<pre>#{better_format}</pre>".html_safe
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_controller_helper.rb
module SessionsControllerHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/views/albums/_form.html.erb
<% action_url = album.persisted? ? album_url(album) : albums_url %>
<% http_method = album.persisted? ? "PATCH" : "POST" %>

<% unless album.errors.full_messages.empty? %>
<ul>
  <% album.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
      
  <label>Name
    <input type="text" name="album[name]" value="<%= album.name %>"
  </label>
  <br>
  
  <br>
  <label>Band
    <select name="album[band_id]">
      <% Band.all.each do |band| %>
      <option
        <%= "selected" if album.band_id == band.id %>
        value="<%= band.id %>">
        <%= band.name %>
      </option>
      <% end %>
    </select>
  </label>
  <br>
  
  <br>
  <label>Year
    <input type="text" name="album[year]" value="<% album.year %>">
  </label>
  <br>
  
  <input type="submit" value="Add Album!">
</form>

app/views/albums/edit.html.erb
<h3>Edit <%= @album.name %></h3>

<%= render "form", album: @album %>

app/views/albums/new.html.erb
<h3>New <%= @band.name %> Album!</h3>

<%= render "form", album: @album %>

app/views/albums/show.html.erb
<h3><%= @album.name %></h3>

<ul>
  <% @album.tracks.each do |track| %>
   <li><%= link_to track.name, track_url(track) %></li>
 <% end %>
</ul>

<ul>
  <li><%= link_to "New Track", new_album_track_url(@album.id)%></li>
  <li><%= link_to "Edit Album", edit_album_url(@album)%></li>
  <li><%= link_to "Destroy Album", album_url(@album), method: :delete%></li>
  <li><%= link_to @album.band.name, band_url(@album.band) %></li>

app/views/bands/_form.html.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% http_method = band.persisted? ? "PATCH" : "POST" %>

<% unless band.errors.full_messages.empty? %>
<ul>
  <% band.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
    
  <label>Band/Musician Name
    <input type="text" name="band[name]" value="<%= band.name%>">
  </label>
  <br>
  
  <br>
  <input type="submit">
</form>

app/views/bands/edit.html.erb
<h3>Edit <%= @band.name %></h3>

<%= render "form", band: @band %>

app/views/bands/index.html.erb
<h3>Bands/Musicians</h3>

<ul>
  <% @bands.each do |band| %>
    <li><%= link_to band.name, band_url(band) %></li>
  <% end %>
</ul>

<%= link_to "New Band/Musician", new_band_url %><br>
<%= link_to "New Album", new_band_album_url(@bands.first) %>

app/views/bands/new.html.erb
<h3>New Band/Musician!</h3>

<%= render "form", band: @band %>

app/views/bands/show.html.erb
<h3><%= @band.name %></h3>

<ul>
  <% @band.albums.each do |album| %>
    <li><%= link_to album.name, album_url(album) %></li>
  <% end %>
</ul>

<ul>
  <li><%= link_to "New album", new_band_album_url(@band.id) %></li>
  <li><%= link_to "Edit band/musician", edit_band_url(@band.id) %></li>
  <li>
    <%= link_to "Delete band/musician", band_url(@band.id), method: :delete %>
  </li>
  <li><%= link_to "All bands/musicians", bands_url %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <!-- <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
   --><%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
  <p><%= current_user.email %></p>
  <%= button_to "Sign Out", session_url, method: :delete %>
<% end %>

<%= yield %>
<br>
</body>
<%= button_to "Bands/Musicians", bands_url, method: :get %>
</html>

app/views/notes/_form.html.erb
<h3>New Note</h3>

<form action="<%= notes_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
    
  <input type="hidden" name="note[track_id]" value="<%= track.id %>">
  
  <label for="note_content">Content</label>
  <br>
  
  <textarea id="note_content" name="note[content]"></textarea>
  <br>
  
  <input type="submit">
</form>

app/views/notes/_note.html.erb
<pre><%= note.content %></pre>
<p>Author: <%= note.user.email %></p>

<% if note.user_id == current_user.id %>
  <%= button_to "Delete note!", note_url(note), method: :delete %>
<% end %>

app/views/tracks/_form.html.erb
<% action_url = track.persisted? ? track_url(track) : tracks_url %>
<% http_method = track.persisted? ? "PATCH" : "POST" %>

<% unless track.errors.full_messages.empty? %>
<ul>
  <% track.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<form action="<%= action_url %>" method="POST" %>
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  
  <label>Track Name
    <input type="text" name="track[name]" value="<%= track.name %>">
  </label>
  <br>
  
  <br>
  <label>Album Name
    <select name="track[album_id]">
        <% Album.all.each do |album| %>
            <option
                <%= "selected" if track.album_id == album.id %>
                value="<%= album.id %>">
                <%= album.name %>
            </option>
        <% end %>
    </select>
  </label>
  <br>

  <br>
  <label>Track #
    <input type="number" name="track[track_num]" value="<%= track.track_num %>">
  </label>
  <br>

  <br>
  <label for="track_lyrics">Lyrics</label>
  <textarea 
    id="track_lyrics" 
    name="track[lyrics]"><%= track.lyrics %>
  </textarea>
  <br>

  <br>
  <input type="submit">
</form>

app/views/tracks/edit.html.erb
<h3>Edit <%= @track.name %></h3>

<%= render "form", track: @track %>

app/views/tracks/new.html.erb
<h3>New <%= @album.name %> Track</h3>

<%= render "form", track: @track %>

app/views/tracks/show.html.erb
<h3><%= @track.name %></h3>

<%= ugly_lyrics(@track.lyrics) %>

<% @track.notes.each do |note| %>
  <p>Note: <%= @track.notes.index(note) + 1 %></p>
  <%= render "notes/note", note: note %>
<% end %>

<%= render "notes/form", track: @track %>

<ul>
  <li><%= link_to "Edit Track", edit_track_url(@track)%></li>
  <li><%= link_to "Delete Track", track_url(@track), method: :delete%></li>
  <li><%= link_to @track.album.name, album_url(@track.album.id)%></li>

app/views/users/new.html.erb
<h3>New User</h3>

<form action="<%= users_url %>" method="POST">
  <input 
    type="hidden" 
    name="authenticity_token" 
    value="<%= form_authenticity_token%>">
    
  <label>Email
    <input type="text" name="user[email]">
  </label>
  <br>
  
  <br>
  <label>Password
    <input type="password" name="user[password]">
  </label>
  <br>
  
  <br>
  <input type="submit">
</form>

app/views/users/show.html.erb
<h3><%= @user.email %></h3>